DeviceMang/Controllers/AutentificationController.cs
using DeviceMang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DeviceMang.Controllers
{
    public class AutentificationController : Controller
    {
        private UsersDevicesDB db = new UsersDevicesDB();
        // GET:Autentification/Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "Email,Password")] User user)
        {
            if (user.Email != null && user.Password != null)
            {
                User dbuser = db.Users.SingleOrDefault(x => x.Email == user.Email);
                if ((dbuser != null) && (dbuser.Password == user.Password))
                {
                    FormsAuthentication.RedirectFromLoginPage(user.Email, false);
                }
                else Response.Write("<div class='alert alert-danger' role='alert'> Please try again! </div>");
                return View();
            }
            else
            {
                Response.Write("<div class='alert alert-danger' role='alert'> Please try again! </div>");
                return View();
            }

        }


        public ActionResult SignUp()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp([Bind(Include = "IdUser,Name,Role,Location,Password,Email")] User user)
        {
            if (user.Name != null && user.Role != null && user.Password != null && user.Email != null && user.Location!=null)
            {
                if (ModelState.IsValid)
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Login");
                }
            }
            else Response.Write("<div class='alert alert-danger' role='alert'> Please try again! </div>"); ;

            return View(user);
        }
        public ActionResult Signu()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

    }


}

DeviceMang/Controllers/UserToDevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeviceMang.Models;

namespace DeviceMang.Controllers
{
    public class UserToDevicesController : Controller
    {
        private UsersDevicesDB db = new UsersDevicesDB();

        // GET: UserToDevices
        public ActionResult Index()
        {
            var userToDevices = db.UserToDevices.Include(u => u.Device).Include(u => u.User);
            return View(userToDevices.ToList());
        }

        // GET: UserToDevices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserToDevice userToDevice = db.UserToDevices.Find(id);
            if (userToDevice == null)
            {
                return HttpNotFound();
            }
            return View(userToDevice);
        }

        // GET: UserToDevices/Create
        public ActionResult Create()
        {
            ViewBag.IdDevice = new SelectList(db.Devices, "IdDevice", "Name");
            ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Name");
            return View();
        }

        // POST: UserToDevices/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IdDevice,IdUser")] UserToDevice userToDevice)
        {
            if (ModelState.IsValid)
            {
                db.UserToDevices.Add(userToDevice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdDevice = new SelectList(db.Devices, "IdDevice", "Name", userToDevice.IdDevice);
            ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Name", userToDevice.IdUser);
            return View(userToDevice);
        }

        // GET: UserToDevices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserToDevice userToDevice = db.UserToDevices.Find(id);
            if (userToDevice == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdDevice = new SelectList(db.Devices, "IdDevice", "Name", userToDevice.IdDevice);
            ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Name", userToDevice.IdUser);
            return View(userToDevice);
        }

        // POST: UserToDevices/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdDevice,IdUser")] UserToDevice userToDevice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userToDevice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdDevice = new SelectList(db.Devices, "IdDevice", "Name", userToDevice.IdDevice);
            ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Name", userToDevice.IdUser);
            return View(userToDevice);
        }

        // GET: UserToDevices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserToDevice userToDevice = db.UserToDevices.Find(id);
            if (userToDevice == null)
            {
                return HttpNotFound();
            }
            return View(userToDevice);
        }

        // POST: UserToDevices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserToDevice userToDevice = db.UserToDevices.Find(id);
            db.UserToDevices.Remove(userToDevice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DeviceMang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Device Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (Request.IsAuthenticated)
    {
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Device Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Users", "Index", "Users")</li>
                            <li>@Html.ActionLink("Devices", "Index", "Devices")</li>
                            <li>@Html.ActionLink("User To Device", "Index", "UserToDevices")</li>
                            <li>@Html.ActionLink("Sign Out", "Signu", "Autentification")</li>
                        </ul>
                    </div>
                </div>
            </div>
    }
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Device Manager</p>
                </footer>
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
        </body>
</html>